# Author: Hao Cheng (cb1ock.github.com)
name: Update deadlines snapshot

on:
    schedule:
        - cron: '0 0 * * *'  # Runs at 00:00

    # push:
    #     branches: [ "main" ]

    # pull_request:
    #     branches: [ "main" ]

    workflow_dispatch:

permissions:
    repository-projects: write
    issues: write
    contents: write  # 修改为 write 权限以允许 push 操作

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GITHUB_TOKEN 进行身份验证

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '16'

            - name: Install Puppeteer
              run: |
                    npm install puppeteer

            - name: Take screenshot
              run: |
                node -e "const puppeteer = require('puppeteer');
                    (async () => {
                        const browser = await puppeteer.launch({
                            args: ['--no-sandbox', '--disable-setuid-sandbox']
                        });
                        const page = await browser.newPage();
                        
                        // 设置更大的视口以显示更多内容
                        await page.setViewport({width: 1280, height: 960});
                        
                        // 访问页面
                        await page.goto('https://huggingface.co/spaces/huggingface/ai-deadlines', {
                            waitUntil: 'networkidle0', // 等待网络请求完成
                            timeout: 60000 // 等待最多60秒
                        });
                        
                        // 等待页面内容加载
                        await page.waitForSelector('.main-content', {timeout: 30000}).catch(() => console.log('正在等待内容加载...'));
                        
                        // 额外等待时间让JavaScript完全执行
                        await page.waitForTimeout(5000);
                        
                        // 确保 Images 目录存在
                        await require('fs').promises.mkdir('./Images', { recursive: true }).catch(() => {});
                        
                        // 截图
                        await page.screenshot({path: './Images/DDL.png', fullPage: true});
                        await browser.close();
                    })();"
            - name: Push changes
              run: |
                    git config --global user.name 'github-actions'
                    git config --global user.email 'github-actions@github.com'
                    git add ./Images/DDL.png
                    git commit -m "Update deadlines snapshot"
                    git push
