name: Update deadlines snapshot

on:
    schedule:
        - cron: '0 0 * * *'  # Runs every day at 00:00

    push:
        branches: [ "main" ]

    pull_request:
        branches: [ "main" ]

    workflow_dispatch:

permissions:
    repository-projects: write
    issues: write
    contents: write  # 修改为 write 权限以允许 push 操作

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GITHUB_TOKEN 进行身份验证

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '16'

            - name: Install Puppeteer
              run: |
                    npm install puppeteer

            - name: Take screenshot
              run: |
                    node -e "const puppeteer = require('puppeteer');
                                        (async () => {
                                            const browser = await puppeteer.launch();
                                            const page = await browser.newPage();
                                            await page.goto('https://aideadlin.es/?sub=CV,ML,NLP');
                                            const content = await page.evaluate(() => {
                                                let element = document.querySelector('#coming_confs');
                                                const endElement = document.querySelector('#past_confs');
                                                let content = '';
                                                while (element && element !== endElement) {
                                                    content += element.outerHTML;
                                                    element = element.nextElementSibling;
                                                }
                                                return content;
                                            });
                                            if (!content) {
                                                console.error('Content not found');
                                                await browser.close();
                                                return;
                                            }
                                            await page.setContent(content); // 设置页面内容
                                            await page.screenshot({path: './Images/DDL.png'}); // 截图
                                            await browser.close();
                                        })();"

            - name: Push changes
              run: |
                    git config --global user.name 'github-actions'
                    git config --global user.email 'github-actions@github.com'
                    git add ./Images/DDL.png
                    git commit -m "Update deadlines snapshot"
                    git push